Import('*')

documentCategory_ = 'game_design'
thisDocument_ = 'concept'
lang_ = 'en_Us'

# now execute template to do actual work
execfile(docBuildEnv.Dir('#').get_abspath()+'/docsrc/generic_template.py')
execfile(docBuildEnv.Dir('#').get_abspath()+'/docsrc/xhtml_article_template.py')
execfile(docBuildEnv.Dir('#').get_abspath()+'/docsrc/pdf_template.py')